import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class subsetsWithDup {

    public static void main(String[] args) {

        int[] nums = {1, 2, 2};

        // Sort the array so that duplicate elements become adjacent.
        // This makes it easy to skip repeated values while backtracking.
        Arrays.sort(nums);

        // Stores the subset currently being constructed.
        ArrayList<Integer> current = new ArrayList<>();

        // Stores all unique subsets generated by recursion.
        ArrayList<List<Integer>> answer = new ArrayList<>();

        // Start recursive backtracking from index 0.
        solve(nums, 0, current, answer);

        System.out.println("Unique subsets : " + answer);
    }

    /**
     * Generates all unique subsets using recursive backtracking.
     *
     * Idea:
     * Every element has two choices:
     * 1. Include the current element.
     * 2. Exclude the current element.
     *
     * While excluding an element, duplicate values are skipped
     * to avoid generating identical subsets.
     *
     * @param nums     Sorted input array
     * @param index    Current position being processed
     * @param current  Current subset being built
     * @param answer   Stores all generated unique subsets
     */
    public static void solve(int[] nums,
                             int index,
                             ArrayList<Integer> current,
                             ArrayList<List<Integer>> answer) {

        /*
         * Base Case
         * Once every element has been processed,
         * the current subset is complete.
         *
         * A copy of the current subset is stored because
         * the original list will continue to change during
         * the backtracking process.
         */
        if (index == nums.length) {
            answer.add(new ArrayList<>(current));
            return;
        }

        /*
         * Choice 1 : Include Element
         * Select the current element and continue exploring.
         */
        current.add(nums[index]);
        solve(nums, index + 1, current, answer);

        /*
         * Backtracking
         * Undo the previous choice so the next recursive
         * branch starts from the original state.
         */
        current.removeLast();

        /*
         * Choice 2 : Exclude Element
         * Skip the current element.
         *
         * Since the array is sorted, skip all consecutive
         * duplicate values before exploring the next branch.
         */
        index = index + 1;

        while (index < nums.length && nums[index] == nums[index - 1]) {
            index++;
        }

        solve(nums, index, current, answer);
    }
}